FROM osrf/ros:ros:jazzy-perception

# Install essential packages

RUN apt update && apt install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    nano \
    vim \
    python3-pip \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    python3-argcomplete


RUN apt update && apt install -y \
    libeigen3-dev \
    libceres-dev \
    libsuitesparse-dev \
    libyaml-cpp-dev \
    libpcap-dev \
    libgoogle-glog-dev \
    libgflags-dev

# RViz2 and display dependencies
RUN apt update && apt install -y \
    ros-jazzy-rviz2 \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    mesa-utils \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*

# Display environment
ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1
ENV ROS_DOMAIN_ID=7

RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc && 

WORKDIR /ros2_ws