FROM ros:jazzy-ros-base

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y \
  build-essential \
  cmake \
  git \
  wget \
  curl \
  nano \
  vim \
  python3-pip \
  python3-colcon-common-extensions \
  python3-rosdep \
  python3-vcstool \
  python3-argcomplete

RUN apt-get update && apt-get install -y \
ros-jazzy-image-transport \
ros-jazzy-cv-bridge \
ros-jazzy-vision-opencv \
&& rm -rf /var/lib/apt/lists/*

RUN rosdep init || true && rosdep update

RUN apt update && apt install -y \
  libeigen3-dev \
  libceres-dev \
  libsuitesparse-dev \
  libyaml-cpp-dev \
  libpcap-dev \
  libgoogle-glog-dev \
  libgflags-dev \
  && rm -rf /var/lib/apt/lists/*

ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1
ENV ROS_DOMAIN_ID=7

RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

WORKDIR /ros2_ws

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]